/* RAZA homepage — reliable local hero + catalogue */
(()=>{
  const SUPABASE_URL='https://iljmxsfcjuutppftsrrt.supabase.co';
  const SUPABASE_KEY=(document.documentElement.innerHTML.match(/sb_publishable_[A-Za-z0-9_-]+/)||[])[0]||'';
  const style=document.createElement('style');
  style.textContent=`
  .hero{display:block!important;padding:0!important;margin:0!important;min-height:0!important;background:#061426!important;overflow:hidden!important}
  .hero-copy{display:none!important}
  .hero-art{display:block!important;position:relative!important;width:100%!important;height:clamp(620px,48vw,760px)!important;min-height:620px!important;overflow:hidden!important;background:radial-gradient(circle at 78% 42%,#1d5b9b 0,#0b2745 34%,#040b15 75%)!important}
  .hero-art:before{content:'';position:absolute;inset:0;background:linear-gradient(90deg,#020a15 0%,#071a30 45%,#071a30aa 62%,#071a3000 100%);z-index:2;pointer-events:none}
  .raza-hero-shell{position:absolute;inset:0;z-index:4;display:grid;grid-template-columns:52% 48%;align-items:center;padding:55px 6vw 70px}
  .raza-hero-copy{max-width:650px;color:#fff}
  .raza-kicker{font:800 11px Manrope,Arial;letter-spacing:4px;color:#f3cd68;margin-bottom:20px}
  .raza-hero-title{margin:0;font:800 clamp(48px,6.2vw,92px)/.88 Manrope,Arial;letter-spacing:-5px}
  .raza-hero-title span{display:block;color:#fff}.raza-hero-title em{font-style:normal;color:#2f86ff}
  .raza-hero-desc{max-width:500px;margin:24px 0;color:#cbd7e6;font:500 15px/1.75 DM Sans,Arial}
  .raza-hero-actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:25px}
  .raza-hero-btn{display:inline-flex;align-items:center;gap:20px;padding:15px 22px;border-radius:8px;background:linear-gradient(135deg,#f4d273,#d9a83a);color:#061426;font:900 11px Manrope;box-shadow:0 14px 35px #0005;transition:.25s}.raza-hero-btn:hover{transform:translateY(-3px)}
  .raza-hero-btn.alt{background:#ffffff12;color:#fff;border:1px solid #ffffff35;backdrop-filter:blur(10px)}
  .raza-trust{display:flex;gap:24px;margin-top:34px;flex-wrap:wrap}.raza-trust div{padding-left:11px;border-left:2px solid #e9c35d}.raza-trust b{display:block;font:800 10px Manrope;letter-spacing:1px}.raza-trust small{display:block;color:#94a5ba;font-size:8px;margin-top:4px}
  .raza-hero-photo{position:relative;height:100%;display:flex;align-items:center;justify-content:center;z-index:5}
  .raza-hero-photo:before{content:'';position:absolute;width:min(34vw,470px);height:min(34vw,470px);border-radius:50%;background:#1a86ff35;filter:blur(35px)}
  .raza-hero-photo img{position:relative;width:auto;height:min(92%,690px);max-width:88%;object-fit:contain;border-radius:22px;box-shadow:0 35px 90px #0008,0 0 0 1px #e9c35d55;display:block;transition:transform .6s ease}
  .raza-hero-photo:hover img{transform:translateY(-7px) scale(1.01)}
  .raza-photo-badge{position:absolute;right:1%;bottom:6%;z-index:7;padding:13px 17px;border-radius:12px;background:#061426dd;border:1px solid #e9c35d66;color:#fff;box-shadow:0 20px 45px #0008;backdrop-filter:blur(12px)}.raza-photo-badge b{display:block;font:900 10px Manrope;letter-spacing:1.4px}.raza-photo-badge small{display:block;color:#9eb0c5;font-size:8px;margin-top:4px}
  .raza-hero-bottom{position:absolute;left:6vw;right:6vw;bottom:18px;z-index:8;display:flex;justify-content:space-between;color:#b9c7d8;font:700 8px Manrope;letter-spacing:2px;text-transform:uppercase}
  .raza-hero-bottom strong{color:#f2cd6b}
  @media(max-width:900px){.hero-art{height:auto!important;min-height:0!important}.raza-hero-shell{position:relative;grid-template-columns:1fr;padding:45px 7vw 35px;min-height:720px}.raza-hero-copy{position:relative;z-index:10}.raza-hero-title{font-size:50px;letter-spacing:-3px}.raza-hero-desc{font-size:14px}.raza-hero-photo{position:absolute;inset:0;opacity:.32}.raza-hero-photo img{height:92%;max-width:75%;filter:saturate(1.05)}.raza-hero-photo:before{width:70vw;height:70vw}.raza-hero-bottom{left:7vw;right:7vw}.raza-photo-badge{display:none}}
  @media(max-width:520px){.raza-hero-shell{min-height:690px;padding:38px 6vw 28px}.raza-hero-title{font-size:42px;letter-spacing:-2.5px}.raza-kicker{font-size:9px;letter-spacing:3px}.raza-hero-desc{font-size:13px;margin:18px 0}.raza-trust{gap:12px;margin-top:25px}.raza-trust b{font-size:8px}.raza-trust small{font-size:7px}.raza-hero-photo{opacity:.25}.raza-hero-photo img{height:88%;max-width:88%;border-radius:16px}.raza-hero-bottom{display:none}}
  `;
  document.head.appendChild(style);
  const art=document.querySelector('.hero-art');
  if(art){art.innerHTML=`<div class="raza-hero-shell"><div class="raza-hero-copy"><div class="raza-kicker">RAZA MOBILE & ELECTRONICS</div><h1 class="raza-hero-title"><span>More than just</span><span><em>electronics.</em></span></h1><p class="raza-hero-desc">New phones, trusted repairing, verified second-hand devices and everyday accessories — all under one roof.</p><div class="raza-hero-actions"><a class="raza-hero-btn" href="#new">Explore Phones <b>→</b></a><a class="raza-hero-btn alt" href="#repair">Book Repair <b>↗</b></a></div><div class="raza-trust"><div><b>100% ORIGINAL</b><small>Products</small></div><div><b>EXPERT SERVICE</b><small>Careful repairs</small></div><div><b>KURUM HAT</b><small>Katihar, Bihar</small></div></div></div><div class="raza-hero-photo"><img src="/assets/raza-hero-portrait.jpg?v=20260912-final" alt="Raza Mobile & Electronics showroom" loading="eager" decoding="async"><div class="raza-photo-badge"><b>THE RAZA EXPERIENCE</b><small>Premium showroom · Local service</small></div></div></div><div class="raza-hero-bottom"><span>NEW PHONES · REPAIRING · SECOND-HAND · ACCESSORIES</span><strong>RAZA / KURUM HAT · KATIHAR</strong></div>`;}
  const money=v=>`₹${Number(v||0).toLocaleString('en-IN')}`;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const section=c=>{const s=`${c?.slug||''} ${c?.name||''}`.toLowerCase().replace(/[-_]+/g,' ');if(s.includes('new phone')||s.includes('new mobile'))return'new';if(s.includes('second hand')||s.includes('used phone')||s.includes('pre owned'))return'used';if(s.includes('accessor'))return'accessories';return'other'};
  const placeholder=p=>`<div class="product-placeholder"><strong>${esc((p.brand||p.name||'R').slice(0,1).toUpperCase())}</strong><span>${esc(p.brand||'RAZA')}</span></div>`;
  const whatsapp=p=>`https://wa.me/919534715178?text=${encodeURIComponent(`Hello Raza Mobile & Electronics, I want to buy ${p.name||'this product'}.`)}`;
  function card(p){const href=p.id?`product.html?id=${encodeURIComponent(p.id)}`:'#';const img=p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='flex'">${placeholder(p)}`:placeholder(p);return `<article class="product-card search-product" data-name="${esc(`${p.name||''} ${p.meta||''} ${p.brand||''}`.toLowerCase())}"><a class="product-card-link" href="${href}"><div class="product-image">${img}<span class="pill">${esc(p.tag||'AVAILABLE')}</span></div><div class="product-info"><small>${esc(p.meta||'')}</small><h3>${esc(p.name||'Product')}</h3><div class="price-row"><span class="price">${esc(p.price||'Price on request')}</span><span class="arrow">↗</span></div></div></a><a class="product-buy" href="${whatsapp(p)}" target="_blank" rel="noopener">Buy / Enquire</a></article>`}
  async function loadCatalogue(){if(!SUPABASE_KEY)return;try{const h={apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`};const [pr,cr]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/products?select=*&is_active=eq.true&order=created_at.desc`,{headers:h}),fetch(`${SUPABASE_URL}/rest/v1/categories?select=id,name,slug&is_active=eq.true`,{headers:h})]);if(!pr.ok)return;const products=await pr.json(),cats=cr.ok?await cr.json():[];const cm={};cats.forEach(c=>cm[c.id]=c);const ids=products.map(p=>p.id).filter(Boolean);let ims=[];if(ids.length){const r=await fetch(`${SUPABASE_URL}/rest/v1/product_images?select=product_id,image_url,sort_order&product_id=in.(${ids.join(',')})&order=sort_order.asc`,{headers:h});if(r.ok)ims=await r.json()}const im={};ims.forEach(x=>{if(!im[x.product_id])im[x.product_id]=x.image_url});const rows=products.map(p=>({...p,section:section(cm[p.category_id]||{}),image:im[p.id],meta:[p.storage,p.condition].filter(Boolean).join(' • ')||'Available',price:money(p.sale_price??p.price),tag:p.condition?'VERIFIED USED':p.is_featured?'FEATURED':'NEW'}));const put=(id,arr,msg)=>{const el=document.getElementById(id);if(el)el.innerHTML=arr.length?arr.map(card).join(''):`<div class="catalog-empty">${msg}</div>`};put('newProducts',rows.filter(p=>p.section==='new'),'No new phones listed yet.');put('usedProducts',rows.filter(p=>p.section==='used'),'No second-hand phones listed yet.');put('accessoryProducts',rows.filter(p=>p.section==='accessories'),'No accessories listed yet.')}catch(e){console.warn('Catalogue:',e)}}
  document.getElementById('siteSearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();document.querySelectorAll('.search-product').forEach(x=>x.style.display=!q||x.dataset.name.includes(q)?'':'none')});document.getElementById('menuBtn')?.addEventListener('click',()=>{const n=document.querySelector('.header nav');if(n)n.style.display=n.style.display==='flex'?'none':'flex'});loadCatalogue();
})();
