const SUPABASE_URL='https://iljmxsfcjuutppftsrrt.supabase.co';
const SUPABASE_ANON_KEY=window.RAZA_SUPABASE_ANON_KEY||'';
const state={products:[],categories:[]};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function api(path,opts={}){if(!SUPABASE_ANON_KEY)throw new Error('Supabase anon key is not configured.');const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{...opts,headers:{apikey:SUPABASE_ANON_KEY,Authorization:'Bearer '+SUPABASE_ANON_KEY,'Content-Type':'application/json',...(opts.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
async function load(){try{state.categories=await api('categories?select=*&order=sort_order.asc');state.products=await api('products?select=*,categories(name),product_images(image_url,sort_order)&order=created_at.desc');render()}catch(e){document.querySelector('#productList').innerHTML='<div class="empty">Supabase connection is not configured yet. Add the public anon key in the deployment environment, never the service-role key.</div>';renderCategories()}}
function render(){document.querySelector('#totalProducts').textContent=state.products.length;document.querySelector('#usedCount').textContent=state.products.filter(p=>/second/i.test(p.categories?.name||'')).length;document.querySelector('#newCount').textContent=state.products.filter(p=>/new/i.test(p.categories?.name||'')).length;document.querySelector('#accessoryCount').textContent=state.products.filter(p=>/accessor/i.test(p.categories?.name||'')).length;const list=document.querySelector('#productList');list.innerHTML=state.products.length?state.products.map(p=>{const img=(p.product_images||[]).sort((a,b)=>a.sort_order-b.sort_order)[0]?.image_url;return `<article class="admin-product"><div class="thumb">${img?`<img src="${esc(img)}" alt="">`:'<span>R</span>'}</div><div><b>${esc(p.name)}</b><small>${esc(p.categories?.name||'')} · ${esc(p.condition||'')}</small></div><strong>${p.price?'₹'+Number(p.price).toLocaleString('en-IN'):'Price on request'}</strong><span class="status">${p.is_active?'LIVE':'HIDDEN'}</span></article>`}).join(''):'<div class="empty">No products yet. Use “Add product” to create your first listing.</div>';renderCategories()}
function renderCategories(){document.querySelector('#categoryList').innerHTML=state.categories.map(c=>`<div class="category"><b>${esc(c.name)}</b><span>${c.is_active?'Active':'Hidden'} · order ${c.sort_order}</span></div>`).join('')}
document.querySelector('#addProduct').onclick=()=>alert('Product editor next: category, title, price, sale price, condition, storage/RAM, stock, description, featured flag and multiple image upload.');
load();
