const SUPABASE_URL='https://iljmxsfcjuutppftsrrt.supabase.co';const SUPABASE_ANON_KEY=window.RAZA_SUPABASE_ANON_KEY||'';const LOOKUP_URL=SUPABASE_URL+'/functions/v1/device-lookup';const state={products:[],categories:[]};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function api(path,opts={}){if(!SUPABASE_ANON_KEY)throw new Error('Supabase anon key is not configured.');const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{...opts,headers:{apikey:SUPABASE_ANON_KEY,Authorization:'Bearer '+SUPABASE_ANON_KEY,'Content-Type':'application/json',...(opts.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
async function load(){try{state.categories=await api('categories?select=*&order=sort_order.asc');state.products=await api('products?select=*,categories(name),product_images(image_url,sort_order)&order=created_at.desc');render()}catch(e){document.querySelector('#productList').innerHTML='<div class="empty">Supabase connection is not configured yet. Add the public anon key in the deployment environment, never the service-role key.</div>';renderCategories()}}
function render(){document.querySelector('#totalProducts').textContent=state.products.length;document.querySelector('#usedCount').textContent=state.products.filter(p=>/second/i.test(p.categories?.name||'')).length;document.querySelector('#newCount').textContent=state.products.filter(p=>/new/i.test(p.categories?.name||'')).length;document.querySelector('#accessoryCount').textContent=state.products.filter(p=>/accessor/i.test(p.categories?.name||'')).length;const list=document.querySelector('#productList');list.innerHTML=state.products.length?state.products.map(p=>{const img=(p.product_images||[]).sort((a,b)=>a.sort_order-b.sort_order)[0]?.image_url;return `<article class="admin-product"><div class="thumb">${img?`<img src="${esc(img)}" alt="">`:'<span>R</span>'}</div><div><b>${esc(p.name)}</b><small>${esc(p.categories?.name||'')} · ${esc(p.condition||'')}</small></div><strong>${p.price?'₹'+Number(p.price).toLocaleString('en-IN'):'Price on request'}</strong><span class="status">${p.is_active?'LIVE':'HIDDEN'}</span></article>`}).join(''):'<div class="empty">No products yet. Use “Add product” to create your first listing.</div>';renderCategories()}
function renderCategories(){document.querySelector('#categoryList').innerHTML=state.categories.map(c=>`<div class="category"><b>${esc(c.name)}</b><span>${c.is_active?'Active':'Hidden'} · order ${c.sort_order}</span></div>`).join('')}
function getVal(id){return document.querySelector(id)?.value?.trim()||''}
function fill(id,val){const el=document.querySelector(id);if(el&&val!==undefined&&val!==null&&val!=='')el.value=Array.isArray(val)?val.join(', '):val}
function extractDevice(raw){const d=raw?.data||raw||{};const pick=(...keys)=>{for(const key of keys){const v=key.split('.').reduce((a,k)=>a?.[k],d);if(v!==undefined&&v!==null&&v!=='')return v}return ''};return {name:pick('name','model','device_name'),description:pick('description','overview'),display:pick('display','display.size','specifications.display'),processor:pick('processor','chipset','specifications.processor'),ram:pick('ram','memory.ram','specifications.ram'),camera:pick('camera','cameras','specifications.camera'),battery:pick('battery','battery.capacity','specifications.battery'),os:pick('os','operating_system','software.os'),dimensions:pick('dimensions','specifications.dimensions'),weight:pick('weight','specifications.weight'),colors:pick('colors','colour','specifications.colors'),network:pick('network','connectivity','specifications.network'),images:pick('images','image_urls','gallery')}}
async function lookupDevice(){const brand=getVal('#brand'),model=getVal('#model'),storage=getVal('#storage');if(!brand||!model){alert('पहले Brand और Model चुनें।');return}const btn=document.querySelector('#lookupBtn');const status=document.querySelector('#autoStatus');btn.disabled=true;btn.textContent='Fetching…';status.textContent='Device database से specifications ला रहे हैं…';try{const r=await fetch(LOOKUP_URL,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_ANON_KEY},body:JSON.stringify({brand,model,storage})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Device lookup failed');const d=extractDevice(j);fill('#productName',d.name||`${brand} ${model}${storage?' '+storage:''}`);fill('#description',d.description);fill('#display',d.display);fill('#processor',d.processor);fill('#ram',d.ram);fill('#camera',d.camera);fill('#battery',d.battery);fill('#os',d.os);fill('#dimensions',d.dimensions);fill('#weight',d.weight);fill('#colors',d.colors);fill('#network',d.network);if(d.images)fill('#apiImages',d.images);status.textContent='✓ Specifications, device information और available images automatically loaded.'}catch(e){console.error(e);status.textContent='Device data नहीं मिला। Model spelling check करें या API response देखें.'}finally{btn.disabled=false;btn.textContent='Auto-fill device'}}
function setMode(){const used=getVal('#productType').toLowerCase().includes('second');document.querySelectorAll('.used-only').forEach(x=>x.style.display=used?'grid':'none');document.querySelectorAll('.new-only').forEach(x=>x.style.display=used?'none':'grid')}
function editor(){const ed=document.querySelector('#editor');if(!ed){alert('Product editor UI अभी deploy नहीं हुआ है। अगला deployment editor modal जोड़ देगा।');return}ed.classList.add('open');document.querySelector('#productForm')?.reset();document.querySelector('#autoStatus').textContent='Brand + Model + Storage चुनकर Auto-fill device दबाएँ।';setMode()}
function closeEditor(){document.querySelector('#editor')?.classList.remove('open')}
document.querySelector('#addProduct')?.addEventListener('click',editor);document.querySelector('#closeEditor')?.addEventListener('click',closeEditor);document.querySelector('#lookupBtn')?.addEventListener('click',lookupDevice);document.querySelector('#productType')?.addEventListener('change',setMode);load();